### ISSUE TITLE
I have repaired the library code in my own fork

### ISSUE THREAD

**Issue by gratefulfrog** [devduino/devduino#13]
It will now work on Linux.  I was not able to test the bluetooth or the wifi examples, though.

find the working fork at:  https://github.com/gratefulfrog/devduino

Cheers,
Bob

**Comment by MaNDRaXe** [comment]
Well, in fact I already did it and you reverted all my changes ...

Plus, you also reverted some code from Alexandre and changed a bunch of things without clear explainations :-/.

**Comment by gratefulfrog** [comment]
I am sorry but I don't understand your comment. Are you upset that I made my own working fork? If you are, I am sorry to have upset you and that was not at all my intention.

If you had working code, I would have been happy to use it. But following the instructions on http://devduino.cc/getting-started/ gave me a library that was unusable.

You are not at all obliged to merge my changes back into your code. I only did it to be able to test the devduino.

Quite frankly, there were lots of errors and I think I fixed them all. I only comment code when I think it adds something, fixing mistakes does not add anything...

Anyway, if you think that this is not a positive contribution, just ignore it :-D

**Comment by MaNDRaXe** [comment]
It looks like you are right about things not working on Linux after my PR was merged. I need to investigate but apparently I screwed up somewhere and only part of the fix was in the PR (includes changes not pushed in the PR :-?).

What made me react is that I renamed many files to fix things following Arduino's conventions and you fixed by changing includes not following those conventions. Since you also rolled back one of Alexandre's commit and touched many files here and there (white spaces, var declarations, etc ...) I considered your whole PR as crap without questioning the reality of the problem you were trying to fix. My bad.

So, even if your fix works (didn't check yet), I think you haven't done it the right way. Arduino's naming convention for lib files is UpperCamelCase and this should be applied to DevDuino project. I'll propose a new PR (complete this time) following this convention.

See #11 for references.

**Comment by gratefulfrog** [comment]
I am sorry that you think I haven't done it the right way.  What I did was fix lots of mistakes. 

I have no idea what you are talking about when you say I reverted Alexandre's changes, because I started from the version on the devduino.cc website, not from the github source. 

I am not aware of Arduino Coding Conventions, but I have since read them. I do not agree with the Arduino philosophy that code should be written so that raw beginners can understand it with ease. C++ is a powerful and complex language. When one writes code in C++, the features of C++ are used, be they "hard to understand" or not.  I am not writing code for children, I write code for myself and my peers.

As I said, my intention was to make working code on Linux. The first step was conforming file names and includes so that the code would compile. I chose to use leadingLowerCamelCase which seemed to be prevalent in your file names. Then, I fixed C++ misuse, multiple definitions, what ever I ran into. Once I could run all the examples, I stopped.  

Of course, there is still plenty of work that could be done to clean up the code, for example remove the file devduinoSprite.cpp which is fully commented out.  There is plenty more that could be done to make the library "industrial quality".

Personally, I have no more time to play with it.  Further, given that you had published defective code that would not even compile, and that I took the time to repair and share my work back with you,  I find your aggressive and critical attitude rather surprising and offensive.

As I said previously, if you don't like my fork then don't use it. But in my opinion, you should be thanking me instead of complaining that I made your code work.

**Comment by MaNDRaXe** [comment]
I think that the problem with Alexandre's commit on RTC is coming from the fact that the archive you downloaded from DevDuino's website was not up-to-date with the repo. That could have been avoided in the PR by rebasing before submitting.

Reading your comment, there's apparently a confusion here. I'm not affiliated with DevDuino, I'm just a contributor like you :-). I'm also doing it on my free time and when you tell me not to use your fork, it's difficult, since it's been merged in the project's master branch after your PR :-).

Regarding the Arduino's conventions, I was just talking about the naming one's. I agree that the lowerCamelCase seems prevalent in the code and just like you I started my own fixing by making it consistent. But includes of external libs are all starting with a capital so I found it weird and dug into Arduino's conventions.

I'm sorry that you found me aggressive but I still think DevDuino's code should follow Arduino's naming conventions for lib files. And consider that being a simple contributor like you, seeing your contribution revert all name changes I made without a word was also pretty unpleasant.
